version: '3.8'
services:
  app-java:
    container_name: java-word
    build: ./api
    ports:
      - 8080:8080
    environment:
      - POSTGRES_URL= jdbc:postgresql://db:5432/postgres
      - POSTGRES_USER= postgres
      - POSTGRES_PASSWORD= postgres
    depends_on:
      - java-db
    networks:
      - appword
  java-db:
    container_name: db
    build: ./db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB= postgres
      - POSTGRES_USER= postgres
      - POSTGRES_PASSWORD= postgres
    volumes:
      - db:/var/lib/postgres/data
    networks:
      - appword
  web-go:
    container_name: web
    build: ./web
    ports: 
     - 8081:80
    depends_on:
      - app-java
    networks:
      - appword
volumes:
  db: {}
networks:
  appword: