version: '3.8'
services:
  app-java:
    container_name: java-word
    image: arielvargas7955/app-words-rox:api-java
    ports:
      - 8080:8080
    environment:
      - POSTGRES_URL=jdbc:postgresql://db:5432/postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - java-db
    networks:
      - appword
    links:
      - java-db:db
  java-db:
    container_name: db
    image: arielvargas7955/app-words-rox:db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgres/data
    networks:
      - appword
  web-go:
    container_name: web
    image: arielvargas7955/app-words-rox:web-go
    ports: 
     - 8081:80
    depends_on:
      - app-java
    networks:
      - appword
    links:
      - app-java:api
volumes:
  db: {}
networks:
  appword: