version: '3.8'
services:
  app-java:
    container_name: java-word
    image: java-v1.0.0
    build: ./api
    ports:
      - 8080:8080
    environment:
      - POSTGRES_URL= jdbc:postgresql://db:5432/postgres
      - POSTGRES_USER= postgres
      - POSTGRES_PASSWORD= postgres
    depends_on:
      - java-db
  java-db:
    container_name: db
    build: ./java-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB= postgres
      - POSTGRES_USER= postgres
      - POSTGRES_PASSWORD= postgres
    volumes:
      - db:/var/lib/postgres/data
  web-go:
    container_name: web
    image: golang:alpine
    build: ./go/src
    ports: 
     - 8080:80
volumes:
  db: {}