version: "3.8"
services:
    db:
        image: mariadb
        ports: 
            - 3306:3306
        # command: --default-authentication-plugin=mysql_native_password
        # restart: always
        environment:
            MYSQL_DATABASE: "devopstravel"
            MYSQL_USER: "codeuser"
            MYSQL_PASSWORD: "test"
            MYSQL_ROOT_PASSWORD: "test"
        volumes:
            - ./database:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    www:
        build: .
        ports: 
            - 80:80
        volumes:
            - ./:/var/www/html
        depends_on:
          - db
        links:
            - db
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin:5.2.1
        links: 
            - db:db
        ports:
            - 8000:80
        depends_on:
          - db
        environment:
            MYSQL_USER: codeuser
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
volumes:
    persistent: